import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {ModeToggle} from "@/components/mode-toggle";
import {cn} from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          inter.className,
          "bg-white dark:bg-gray-900"
          )}>
        <ThemeProvider attribute="class"
                       defaultTheme="system"
                       enableSystem>
          {children}
          <ModeToggle/>
        </ThemeProvider>
      </body>
    </html>
  );
}
